name: terraform-infra-code-generic code
on:
   workflow_dispatch
    


# on:
#   pull_request:
#     branches:
#       - main
#   push:
#     branches:
#       - main
#       - features/*

permissions:
  id-token: write
  contents: read
  issues: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v5.0.0

      - name: azure_login
        uses: Azure/login@v2.3.0
        with:  
          client-id: ${{secrets.AZURE_SECRET_ID}}
          tenant-id: ${{secrets.AZURE_TENANT_ID}}
          subscription-id: ${{secrets.AZURE_SUBSCRIPTION_ID}}

      - name: terraform-setup
        uses: hashicorp/setup-terraform@v2.0.3    
      
      - name: terraform init
        working-directory: ./environment/dev
        run: terraform init    

      - name: terraform fmt
        working-directory: ./environment/dev
        run: terraform fmt         

      - name: terraform validate
        working-directory: ./environment/dev
        run: terraform validate 
      
      - name: terraform plan
        working-directory: ./environment/dev
        run: terraform plan
        
  apply:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    environment: dev
    needs: build 
    steps:
      - name: checkout
        uses: actions/checkout@v5.0.0
       
      - name: azure login
        uses: Azure/login@v2.3.0
        with:  
          client-id: ${{secrets.AZURE_SECRET_ID}}
          tenant-id: ${{secrets.AZURE_TENANT_ID}}
          subscription-id: ${{secrets.AZURE_SUBSCRIPTION_ID}}

      - name: terraform-setup
        uses: hashicorp/setup-terraform@v2.0.3         
      
      - name: terraform init
        working-directory: ./environment/dev
        run: terraform init

      - name: terraform validate
        working-directory: ./environment/dev
        run: terraform validate

      - name: terraform apply
        working-directory: ./environment/dev
        run: terraform apply --auto-approve
      
  destroy:
    name: terraform destroy when apply failure
    runs-on: ubuntu-latest
    environment: dev
    needs: apply
    if: failure()
    steps:
      - name: checkout
        uses: actions/checkout@v5.0.0
       
      - name: azure login
        uses: Azure/login@v2.3.0
        with:  
          client-id: ${{secrets.AZURE_SECRET_ID}}
          tenant-id: ${{secrets.AZURE_TENANT_ID}}
          subscription-id: ${{secrets.AZURE_SUBSCRIPTION_ID}}

      - name: terraform-setup
        uses: hashicorp/setup-terraform@v2.0.3         
      
      - name: terraform init
        working-directory: ./environment/dev
        run: terraform init



      - name: terraform destroy
        working-directory: ./environment/dev
        run: terraform destroy --auto-approve
      
